### ISSUE TITLE
GitHub上成功，但实际上没有打卡

### ISSUE THREAD

**Issue by Charlestar** [maxco2/LoveAndPeaceReport#2]
[相似问题](https://github.com/kottory/NJU-health-report/issues/30)
不知道是否有什么解决方式？

**Comment by maxco2** [comment]
最新的 commit 我本地测试解决了

**Comment by maxco2** [comment]
貌似是针对ua的直接封锁

**Comment by Charlestar** [comment]
> 最新的 commit 我本地测试解决了

好的！感谢维护！

**Comment by kottory** [comment]
改成随机ua，不然还是会针对封锁。我也是看到这一点才跑路的）
